Name:           ros-hydro-scitos-docking
Version:        0.0.4
Release:        0%{?dist}
Summary:        ROS scitos_docking package

Group:          Development/Libraries
License:        MIT
URL:            https://github.com/strands-project/scitos_apps
Source0:        %{name}-%{version}.tar.gz

Requires:       blas-devel
Requires:       boost-devel
Requires:       gsl
Requires:       ncurses-devel
Requires:       ros-hydro-actionlib
Requires:       ros-hydro-actionlib-msgs
Requires:       ros-hydro-dynamic-reconfigure
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-image-transport
Requires:       ros-hydro-message-runtime
Requires:       ros-hydro-mongodb-store
Requires:       ros-hydro-move-base-msgs
Requires:       ros-hydro-nav-msgs
Requires:       ros-hydro-opencv2
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospy
Requires:       ros-hydro-scitos-msgs
Requires:       ros-hydro-scitos-teleop
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-tf
BuildRequires:  blas-devel
BuildRequires:  boost-devel
BuildRequires:  gsl
BuildRequires:  ncurses-devel
BuildRequires:  ros-hydro-actionlib
BuildRequires:  ros-hydro-actionlib-msgs
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-dynamic-reconfigure
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-image-transport
BuildRequires:  ros-hydro-message-generation
BuildRequires:  ros-hydro-mongodb-store
BuildRequires:  ros-hydro-move-base-msgs
BuildRequires:  ros-hydro-nav-msgs
BuildRequires:  ros-hydro-opencv2
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-scitos-msgs
BuildRequires:  ros-hydro-scitos-teleop
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-tf

%description
The charging package providing a visual charging action service for the scitos
robot.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Mon Oct 13 2014 gestom <tkrajnik@lincoln.ac.uk> - 0.0.4-0
- Autogenerated by Bloom

* Mon Sep 22 2014 gestom <tkrajnik@lincoln.ac.uk> - 0.0.3-0
- Autogenerated by Bloom

* Mon Sep 22 2014 gestom <tkrajnik@lincoln.ac.uk> - 0.0.1-0
- Autogenerated by Bloom

* Mon Sep 22 2014 gestom <tkrajnik@lincoln.ac.uk> - 0.0.2-0
- Autogenerated by Bloom

